/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLogoutRouteImport } from './routes/_public/logout'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppTradeActivityIndexRouteImport } from './routes/_authenticated/_app/trade-activity/index'
import { Route as AuthenticatedAppTradeActivitySummaryRouteImport } from './routes/_authenticated/_app/trade-activity/summary'
import { Route as AuthenticatedAppTradeActivityBlockLevelRouteImport } from './routes/_authenticated/_app/trade-activity/block-level'
import { Route as AuthenticatedAppTradeActivityAllocationLevelRouteImport } from './routes/_authenticated/_app/trade-activity/allocation-level'
import { Route as AuthenticatedAppTradeActivityBlockLevelIndexRouteImport } from './routes/_authenticated/_app/trade-activity/block-level/index'
import { Route as AuthenticatedAppTradeActivityAllocationLevelIndexRouteImport } from './routes/_authenticated/_app/trade-activity/allocation-level/index'
import { Route as AuthenticatedAppTradeActivityBlockLevelFxOptionsRouteImport } from './routes/_authenticated/_app/trade-activity/block-level/fx-options'
import { Route as AuthenticatedAppTradeActivityBlockLevelFxCashRouteImport } from './routes/_authenticated/_app/trade-activity/block-level/fx-cash'
import { Route as AuthenticatedAppTradeActivityAllocationLevelFxOptionsRouteImport } from './routes/_authenticated/_app/trade-activity/allocation-level/fx-options'
import { Route as AuthenticatedAppTradeActivityAllocationLevelFxCashRouteImport } from './routes/_authenticated/_app/trade-activity/allocation-level/fx-cash'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLogoutRoute = PublicLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppTradeActivityIndexRoute =
  AuthenticatedAppTradeActivityIndexRouteImport.update({
    id: '/trade-activity/',
    path: '/trade-activity/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTradeActivitySummaryRoute =
  AuthenticatedAppTradeActivitySummaryRouteImport.update({
    id: '/trade-activity/summary',
    path: '/trade-activity/summary',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTradeActivityBlockLevelRoute =
  AuthenticatedAppTradeActivityBlockLevelRouteImport.update({
    id: '/trade-activity/block-level',
    path: '/trade-activity/block-level',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTradeActivityAllocationLevelRoute =
  AuthenticatedAppTradeActivityAllocationLevelRouteImport.update({
    id: '/trade-activity/allocation-level',
    path: '/trade-activity/allocation-level',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTradeActivityBlockLevelIndexRoute =
  AuthenticatedAppTradeActivityBlockLevelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppTradeActivityBlockLevelRoute,
  } as any)
const AuthenticatedAppTradeActivityAllocationLevelIndexRoute =
  AuthenticatedAppTradeActivityAllocationLevelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppTradeActivityAllocationLevelRoute,
  } as any)
const AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute =
  AuthenticatedAppTradeActivityBlockLevelFxOptionsRouteImport.update({
    id: '/fx-options',
    path: '/fx-options',
    getParentRoute: () => AuthenticatedAppTradeActivityBlockLevelRoute,
  } as any)
const AuthenticatedAppTradeActivityBlockLevelFxCashRoute =
  AuthenticatedAppTradeActivityBlockLevelFxCashRouteImport.update({
    id: '/fx-cash',
    path: '/fx-cash',
    getParentRoute: () => AuthenticatedAppTradeActivityBlockLevelRoute,
  } as any)
const AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute =
  AuthenticatedAppTradeActivityAllocationLevelFxOptionsRouteImport.update({
    id: '/fx-options',
    path: '/fx-options',
    getParentRoute: () => AuthenticatedAppTradeActivityAllocationLevelRoute,
  } as any)
const AuthenticatedAppTradeActivityAllocationLevelFxCashRoute =
  AuthenticatedAppTradeActivityAllocationLevelFxCashRouteImport.update({
    id: '/fx-cash',
    path: '/fx-cash',
    getParentRoute: () => AuthenticatedAppTradeActivityAllocationLevelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/logout': typeof PublicLogoutRoute
  '/trade-activity/allocation-level': typeof AuthenticatedAppTradeActivityAllocationLevelRouteWithChildren
  '/trade-activity/block-level': typeof AuthenticatedAppTradeActivityBlockLevelRouteWithChildren
  '/trade-activity/summary': typeof AuthenticatedAppTradeActivitySummaryRoute
  '/trade-activity': typeof AuthenticatedAppTradeActivityIndexRoute
  '/trade-activity/allocation-level/fx-cash': typeof AuthenticatedAppTradeActivityAllocationLevelFxCashRoute
  '/trade-activity/allocation-level/fx-options': typeof AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute
  '/trade-activity/block-level/fx-cash': typeof AuthenticatedAppTradeActivityBlockLevelFxCashRoute
  '/trade-activity/block-level/fx-options': typeof AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute
  '/trade-activity/allocation-level/': typeof AuthenticatedAppTradeActivityAllocationLevelIndexRoute
  '/trade-activity/block-level/': typeof AuthenticatedAppTradeActivityBlockLevelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/logout': typeof PublicLogoutRoute
  '/trade-activity/summary': typeof AuthenticatedAppTradeActivitySummaryRoute
  '/trade-activity': typeof AuthenticatedAppTradeActivityIndexRoute
  '/trade-activity/allocation-level/fx-cash': typeof AuthenticatedAppTradeActivityAllocationLevelFxCashRoute
  '/trade-activity/allocation-level/fx-options': typeof AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute
  '/trade-activity/block-level/fx-cash': typeof AuthenticatedAppTradeActivityBlockLevelFxCashRoute
  '/trade-activity/block-level/fx-options': typeof AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute
  '/trade-activity/allocation-level': typeof AuthenticatedAppTradeActivityAllocationLevelIndexRoute
  '/trade-activity/block-level': typeof AuthenticatedAppTradeActivityBlockLevelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/logout': typeof PublicLogoutRoute
  '/_authenticated/_app/trade-activity/allocation-level': typeof AuthenticatedAppTradeActivityAllocationLevelRouteWithChildren
  '/_authenticated/_app/trade-activity/block-level': typeof AuthenticatedAppTradeActivityBlockLevelRouteWithChildren
  '/_authenticated/_app/trade-activity/summary': typeof AuthenticatedAppTradeActivitySummaryRoute
  '/_authenticated/_app/trade-activity/': typeof AuthenticatedAppTradeActivityIndexRoute
  '/_authenticated/_app/trade-activity/allocation-level/fx-cash': typeof AuthenticatedAppTradeActivityAllocationLevelFxCashRoute
  '/_authenticated/_app/trade-activity/allocation-level/fx-options': typeof AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute
  '/_authenticated/_app/trade-activity/block-level/fx-cash': typeof AuthenticatedAppTradeActivityBlockLevelFxCashRoute
  '/_authenticated/_app/trade-activity/block-level/fx-options': typeof AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute
  '/_authenticated/_app/trade-activity/allocation-level/': typeof AuthenticatedAppTradeActivityAllocationLevelIndexRoute
  '/_authenticated/_app/trade-activity/block-level/': typeof AuthenticatedAppTradeActivityBlockLevelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/trade-activity/allocation-level'
    | '/trade-activity/block-level'
    | '/trade-activity/summary'
    | '/trade-activity'
    | '/trade-activity/allocation-level/fx-cash'
    | '/trade-activity/allocation-level/fx-options'
    | '/trade-activity/block-level/fx-cash'
    | '/trade-activity/block-level/fx-options'
    | '/trade-activity/allocation-level/'
    | '/trade-activity/block-level/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/trade-activity/summary'
    | '/trade-activity'
    | '/trade-activity/allocation-level/fx-cash'
    | '/trade-activity/allocation-level/fx-options'
    | '/trade-activity/block-level/fx-cash'
    | '/trade-activity/block-level/fx-options'
    | '/trade-activity/allocation-level'
    | '/trade-activity/block-level'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_app'
    | '/_public/login'
    | '/_public/logout'
    | '/_authenticated/_app/trade-activity/allocation-level'
    | '/_authenticated/_app/trade-activity/block-level'
    | '/_authenticated/_app/trade-activity/summary'
    | '/_authenticated/_app/trade-activity/'
    | '/_authenticated/_app/trade-activity/allocation-level/fx-cash'
    | '/_authenticated/_app/trade-activity/allocation-level/fx-options'
    | '/_authenticated/_app/trade-activity/block-level/fx-cash'
    | '/_authenticated/_app/trade-activity/block-level/fx-options'
    | '/_authenticated/_app/trade-activity/allocation-level/'
    | '/_authenticated/_app/trade-activity/block-level/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/logout': {
      id: '/_public/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PublicLogoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/trade-activity/': {
      id: '/_authenticated/_app/trade-activity/'
      path: '/trade-activity'
      fullPath: '/trade-activity'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trade-activity/summary': {
      id: '/_authenticated/_app/trade-activity/summary'
      path: '/trade-activity/summary'
      fullPath: '/trade-activity/summary'
      preLoaderRoute: typeof AuthenticatedAppTradeActivitySummaryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trade-activity/block-level': {
      id: '/_authenticated/_app/trade-activity/block-level'
      path: '/trade-activity/block-level'
      fullPath: '/trade-activity/block-level'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityBlockLevelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trade-activity/allocation-level': {
      id: '/_authenticated/_app/trade-activity/allocation-level'
      path: '/trade-activity/allocation-level'
      fullPath: '/trade-activity/allocation-level'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityAllocationLevelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trade-activity/block-level/': {
      id: '/_authenticated/_app/trade-activity/block-level/'
      path: '/'
      fullPath: '/trade-activity/block-level/'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityBlockLevelIndexRouteImport
      parentRoute: typeof AuthenticatedAppTradeActivityBlockLevelRoute
    }
    '/_authenticated/_app/trade-activity/allocation-level/': {
      id: '/_authenticated/_app/trade-activity/allocation-level/'
      path: '/'
      fullPath: '/trade-activity/allocation-level/'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityAllocationLevelIndexRouteImport
      parentRoute: typeof AuthenticatedAppTradeActivityAllocationLevelRoute
    }
    '/_authenticated/_app/trade-activity/block-level/fx-options': {
      id: '/_authenticated/_app/trade-activity/block-level/fx-options'
      path: '/fx-options'
      fullPath: '/trade-activity/block-level/fx-options'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityBlockLevelFxOptionsRouteImport
      parentRoute: typeof AuthenticatedAppTradeActivityBlockLevelRoute
    }
    '/_authenticated/_app/trade-activity/block-level/fx-cash': {
      id: '/_authenticated/_app/trade-activity/block-level/fx-cash'
      path: '/fx-cash'
      fullPath: '/trade-activity/block-level/fx-cash'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityBlockLevelFxCashRouteImport
      parentRoute: typeof AuthenticatedAppTradeActivityBlockLevelRoute
    }
    '/_authenticated/_app/trade-activity/allocation-level/fx-options': {
      id: '/_authenticated/_app/trade-activity/allocation-level/fx-options'
      path: '/fx-options'
      fullPath: '/trade-activity/allocation-level/fx-options'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityAllocationLevelFxOptionsRouteImport
      parentRoute: typeof AuthenticatedAppTradeActivityAllocationLevelRoute
    }
    '/_authenticated/_app/trade-activity/allocation-level/fx-cash': {
      id: '/_authenticated/_app/trade-activity/allocation-level/fx-cash'
      path: '/fx-cash'
      fullPath: '/trade-activity/allocation-level/fx-cash'
      preLoaderRoute: typeof AuthenticatedAppTradeActivityAllocationLevelFxCashRouteImport
      parentRoute: typeof AuthenticatedAppTradeActivityAllocationLevelRoute
    }
  }
}

interface AuthenticatedAppTradeActivityAllocationLevelRouteChildren {
  AuthenticatedAppTradeActivityAllocationLevelFxCashRoute: typeof AuthenticatedAppTradeActivityAllocationLevelFxCashRoute
  AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute: typeof AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute
  AuthenticatedAppTradeActivityAllocationLevelIndexRoute: typeof AuthenticatedAppTradeActivityAllocationLevelIndexRoute
}

const AuthenticatedAppTradeActivityAllocationLevelRouteChildren: AuthenticatedAppTradeActivityAllocationLevelRouteChildren =
  {
    AuthenticatedAppTradeActivityAllocationLevelFxCashRoute:
      AuthenticatedAppTradeActivityAllocationLevelFxCashRoute,
    AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute:
      AuthenticatedAppTradeActivityAllocationLevelFxOptionsRoute,
    AuthenticatedAppTradeActivityAllocationLevelIndexRoute:
      AuthenticatedAppTradeActivityAllocationLevelIndexRoute,
  }

const AuthenticatedAppTradeActivityAllocationLevelRouteWithChildren =
  AuthenticatedAppTradeActivityAllocationLevelRoute._addFileChildren(
    AuthenticatedAppTradeActivityAllocationLevelRouteChildren,
  )

interface AuthenticatedAppTradeActivityBlockLevelRouteChildren {
  AuthenticatedAppTradeActivityBlockLevelFxCashRoute: typeof AuthenticatedAppTradeActivityBlockLevelFxCashRoute
  AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute: typeof AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute
  AuthenticatedAppTradeActivityBlockLevelIndexRoute: typeof AuthenticatedAppTradeActivityBlockLevelIndexRoute
}

const AuthenticatedAppTradeActivityBlockLevelRouteChildren: AuthenticatedAppTradeActivityBlockLevelRouteChildren =
  {
    AuthenticatedAppTradeActivityBlockLevelFxCashRoute:
      AuthenticatedAppTradeActivityBlockLevelFxCashRoute,
    AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute:
      AuthenticatedAppTradeActivityBlockLevelFxOptionsRoute,
    AuthenticatedAppTradeActivityBlockLevelIndexRoute:
      AuthenticatedAppTradeActivityBlockLevelIndexRoute,
  }

const AuthenticatedAppTradeActivityBlockLevelRouteWithChildren =
  AuthenticatedAppTradeActivityBlockLevelRoute._addFileChildren(
    AuthenticatedAppTradeActivityBlockLevelRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppTradeActivityAllocationLevelRoute: typeof AuthenticatedAppTradeActivityAllocationLevelRouteWithChildren
  AuthenticatedAppTradeActivityBlockLevelRoute: typeof AuthenticatedAppTradeActivityBlockLevelRouteWithChildren
  AuthenticatedAppTradeActivitySummaryRoute: typeof AuthenticatedAppTradeActivitySummaryRoute
  AuthenticatedAppTradeActivityIndexRoute: typeof AuthenticatedAppTradeActivityIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppTradeActivityAllocationLevelRoute:
    AuthenticatedAppTradeActivityAllocationLevelRouteWithChildren,
  AuthenticatedAppTradeActivityBlockLevelRoute:
    AuthenticatedAppTradeActivityBlockLevelRouteWithChildren,
  AuthenticatedAppTradeActivitySummaryRoute:
    AuthenticatedAppTradeActivitySummaryRoute,
  AuthenticatedAppTradeActivityIndexRoute:
    AuthenticatedAppTradeActivityIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicLogoutRoute: typeof PublicLogoutRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicLogoutRoute: PublicLogoutRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
